### ISSUE TITLE
Error viewing post

### ISSUE THREAD

**Issue by icewater** [j0ack/microbe#1] opened 2015-03-31 21:35 UTC
url http://localhost:8000/posts/microbe-test-post/

    File "/projects/mlsflask/venv/lib/python2.7/site-packages/markdown/__init__.py", line 355, in convert

    if not source.strip():

    AttributeError: 'Content' object has no attribute 'strip'

Any ideas?

**Comment by j0ack** [comment] 2015-04-01 06:55
Hello @icewater, thank you for your feedback

Microbe depends on [Flask-Flatpages](https://github.com/SimonSapin/Flask-FlatPages) to render pages and posts.

I think the problem comes from the new version of Flask-Flatpages which modify the way the renderer function is called. You can see if you use it with

    $ pip show flask-flatpages

If it is the version 0.6, you need to downgrade to version 0.5 with the following commands

    $ pip install flask-flatpages==0.5

I'll look into this to fix that as soon as possible. Feel free to contact me if the problem is not fixed.

**Comment by haludeis** [comment] 2015-05-03 06:47
Hello,
I had the same problem and downgrade flask-flatpages to 0.5 resolve it.
It's a great app thank.
 (sorry for my english)

**Comment by j0ack** [comment] 2015-05-04 06:50
Hi @haludeis 

I'm glad that this app suit your needs. 

If you tell me that downgrading flask-flatpages fix the problem I will update the requirements and close the issue. 

Can I ask you where you hear about this project ?

**Comment by haludeis** [comment] 2015-05-04 12:58
> Can I ask you how did you hear about this project ? 

When looking for a simpler way to manage a blog than through django.
Looking through google I came across this.
http://crunchbang-fr.org/forum/viewtopic.php?id=2586

**Comment by j0ack** [comment] 2015-06-30 09:38
Fixed in 1fb2dc6

**Closed by j0ack** 2015-06-30 09:38 UTC
Labels: bug
